version: '2.2'
services:
  spring-boot:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker-spring-boot
    ports:
      - 8888
    networks:
      - network1
 
networks:
  network1: